name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t my-node-app:${{ github.sha }} .

    - name: Run Tests
      run: |
        docker run --rm my-node-app:${{ github.sha }} npm test

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-node-app:${{ github.sha }}

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: amolac_github_workflow
        SONAR_ORGANIZATION: amolac
      with:
        args: >
          -Dsonar.projectKey=amolac_github_workflow
          -Dsonar.organization=amolac
          -Dsonar.host.url=https://sonarcloud.io

  push-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag my-node-app:${{ github.sha }} my-docker-repo/my-node-app:${{ github.sha }}
        docker push my-docker-repo/my-node-app:${{ github.sha }}

  update-manifest:
    needs: push-image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout manifest repository
      uses: actions/checkout@v2
      with:
        repository: amolac/manifest-repo
        token: ${{ secrets.G_TOKEN }}

    - name: Update Manifest File
      run: |
        echo "Updating manifest file..."
        echo "image: my-docker-repo/my-node-app:${{ github.sha }}" >> manifest.yml
        git config --global user.email "amolchoorappady@gmail.com"
        git config --global user.name "Amol Choorappady"
        git add manifest.yml
        git commit -m "Update manifest with new image version"
        git push origin main

