name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: amolchoorappady/my-node-app
      MANIFEST_FILE: deployment.yml   # update if your manifest file has a different name

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .

    - name: Run Tests
      run: |
        npm test

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: amolchoorappady/my-node-app:${{ github.sha }}

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: amolac_github_workflow
        SONAR_ORGANIZATION: amolac
      with:
        args: >
          -Dsonar.projectKey=amolac_github_workflow
          -Dsonar.organization=amolac
          -Dsonar.host.url=https://sonarcloud.io

    - name: Push Docker Image
      run: |
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:latest

    - name: Checkout manifest repository
      uses: actions/checkout@v2
      with:
        repository: amolac/manifest-repo
        token: ${{ secrets.G_TOKEN }}
        path: manifest-repo

    - name: Update Deployment Image in Manifest
      run: |
        cd manifest-repo
        git config user.email "amolchoorappady@gmail.com"
        git config user.name "Amol Choorappady"
        # Replace the image tag in deployment.yml
        sed -i "s|\($IMAGE_NAME:\).*|\1${{ github.sha }}|" $MANIFEST_FILE
        git add $MANIFEST_FILE
        git commit -m "Update deployment image to ${{ github.sha }}"
        git push origin main
